### ISSUE TITLE
Issue with NATS MTLS exclusion

### ISSUE THREAD

**Issue by kscarlett** [stefanprodan/istio-gke#12]
The last commit changed the NATS MTLS exclusion to the following:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: "nats-no-mtls"
    namespace: {{ .Release.Namespace }}
spec:
    host: "nats.openfaas.svc.cluster.local"
    trafficPolicy:
        tls:
            mode: DISABLE
```

The template in the namespace causes the apply to fail in a cluster freshly set up following all the steps here.

I have been able to fix this by using the namespace "openfaas", as was used before.
