### ISSUE TITLE
question about virtual services

### ISSUE THREAD

**Issue by Karnich** [stefanprodan/istio-gke#7]
Hi Stefan

I hope you could answer my question. It is not directly an issue with your repository, but im following a lot of your guides and need some help >.< 

If i have a service in the default namespace that wants to reach a service in another namespace.. i use `<name>.<namespace>.svc.cluster.local`
but if i wanna split that traffic between two services using weight: i have the following VS in the default namespace:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
  namespace: default
spec:
  hosts:
  - backend
  http:
  - route:
    - destination:
        host: backend.mynamespace.svc.cluster.local
      weight: 50
  - route:
    - destination:
        host: backend-management.mynamespace.svc.cluster.local
      weight: 50
```

If my service in default tries to use `http://backend:port`to access it, it fails
I need the full `http://backend.namespace.svc.cluster.local:port`for it to work, but then my traffic is not split?

What am i doing wrong?

**Comment by stefanprodan** [comment]
Create a virtual service in the namespace where the backend is to overwrite the ClusterIP service:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
  namespace: test
spec:
  hosts:
  - backend
  http:
  - route:
    - destination:
        host: backend.test
        port:
          number: 8080
      weight: 50
  - route:
    - destination:
        host: backend-v2.test
        port:
          number: 8080
      weight: 50
```  

Make sure you have two ClusterIP services in the `test` namespace as in `backend` and `backend-v2`.

Now from the default namespace, an app will call `backend.test:port` and the traffic will be balanced between the 2 backends. Also make sure the default namespace has the sidecar injector enabled.
